name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bilibili-live-suit-emoji.user.js
          path: ./dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/bilibili-live-suit-emoji.user.js
          token: ${{ secrets.GH_TOKEN }}
